meta_product_name: "Hopla"
meta_title: "Hopla - Hospitality Planning made easy, clear and flexible"
meta_description: "Hopla - Hospitality Planning made easy, clear and flexible"
meta_image: "hopla-logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
